name: Build, Test and Lint
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml

  test:
    name: Test
    uses: ./.github/workflows/test.yaml

  build:
    name: Build
    needs: [ "lint", "test" ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yaml