name: Build, Test and Lint
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml

  test:
    name: Test
    uses: ./.github/workflows/test.yaml

  build:
    name: Build
    uses: ./.github/workflows/build.yaml